### ISSUE TITLE
Time based MoveTo() methode

### ISSUE THREAD

**Issue by raoul596** [riflosnake/HumanCursor#6]
Hi,

It would be a nice and usefull feature if the MoveTo() methode has a parameter which sets the time in which the movement will take place. Probably a mouse speed should also be defined so that the mouse would not go over the screen at crazy speeds.

Is this already possible and how would I implement this?

**Comment by riflosnake** [comment]
The SystemCursor has the `duration` parameter on `move_to` method, which sets the time it takes for it to move from starting point to destination, thus also modifying its speed.

The WebCursor unfortunately doesn't have it, maybe I will add it some time soon.
