### ISSUE TITLE
move_to requires a WebElement

### ISSUE THREAD

**Issue by 0z0sk0** [riflosnake/HumanCursor#7]
```
cursor = WebCursor(driver)
cursor.move_by_offset(450, 600)
```

```
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    cursor.move_by_offset(450, 600)
  File "Python311\Lib\site-packages\humancursor\web_cursor.py", line 74, in move_by_offset
    self.origin_coordinates = self.human.move_to([x, y], absolute_offset=True, steady=steady)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\humancursor\utilities\web_adjuster.py", line 119, in move_to
    self.__action.move_to_element(element_or_pos)
  File "Python311\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
  File "Python311\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
```

**Comment by 0z0sk0** [comment]
This happens with headless chrome driver, i think its a bug because window of browser does not exists for real or has size like a 0x0, therefore **move_to** function in **Web_Adjuster.py** raise a **MoveTargetOutOfBoundsException**

**Comment by riflosnake** [comment]
Maybe try this : 

```python
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('window-size=1920x1480')
```
The last argument sets the window size.

**Comment by 0z0sk0** [comment]
Thank you for help, I found the problem, it occurs with the new `--headless=new` flag, but does not occur with `--headless`.

I think we need to solve the problem with [new headless policy](https://developer.chrome.com/docs/chromium/new-headless). Because soon old headless flag will become deprecated.

**Comment by riflosnake** [comment]
That is kinda weird that the new version causes this error and the old one not.

 I think it is counter-intuitive to use headless browser and humancursor together, but anyways this is not a reason to not fix the bug you mentioned soon.

**Comment by 0z0sk0** [comment]
HumanCursor is very useful in any case, because many sites collect mouse movement events, and based on this they can judge the “humanity” of the browser. Thanks for your work!

**Comment by riflosnake** [comment]
I was checking yesterday how the cursor was moving and it was not moving fluently, when I first coded and published the package it was moving very smoothly on Chrome/Edge browser.

Are you seeing the same jittery movement?
